# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core
variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '79573c34-3a9c-4a48-8707-22f6f0cc157e'
  NUGET_XMLDOC_MODE: skip
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  FunctionsPackageName: functions-package
  WebApiPackageName: webapi-package
  IntegrationTestPackageName: integrationtest-package

trigger:
  - master

pool:
  name: "Azure Pipelines"
  vmImage: "windows-latest"

stages:
  - stage: build
    displayName:  Build
    variables:
      - name: ResourceGroupName
        value: az-backendchallengetest0-rg
      - name: Location
        value: Australia Southeast 
      - name: DeploymentServiceConnectionName
        value: BackEndChallenge-SVC
    jobs:
      - job: build_functionApp
        displayName: Build Function App
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 6"
            inputs:
              version: "6.0.x"
          - task: DotNetCoreCLI@2
            displayName: "Publish Function Package"
            inputs:
              command: "publish"
              projects: "$(Build.SourcesDirectory)/azChallengeFA-Customer/CustomerAppFunction.csproj"
              arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)/$(FunctionsPackageName)"
              publishWebProjects: false
          - task: PublishPipelineArtifact@0
            displayName: "Publish Artifact: $(FunctionsPackageName)"
            inputs:
              artifactName: "$(FunctionsPackageName)"
              targetPath: "$(Build.ArtifactStagingDirectory)/$(FunctionsPackageName)"
  - stage: deploy
    displayName: "Deploy Function App"  
    condition: succeeded()
    variables: 
      - name: ResourceGroupName
        value: az-backendchallengetest0-rg
      - name: Location
        value: Australia Southeast 
      - name: DeploymentServiceConnectionName
        value: BackEndChallenge-SVC
    jobs:
      - deployment: deploy_functions_binaries
        displayName: "Deploy Functions"
        environment: "BackEndChallenge-Dev"    
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@0
                  displayName: "Download Artifact: $(FunctionsPackageName)"
                  inputs:
                    artifactName: "$(FunctionsPackageName)"
                    targetPath: $(System.DefaultWorkingDirectory)/$(FunctionsPackageName)

                - task: ARM Outputs@5
                  displayName: "Fetch ARM Outputs"
                  inputs:
                    ConnectedServiceNameARM:  "${{ variables.DeploymentServiceConnectionName }}"
                    resourceGroupName: "$(ResourceGroupName)"
                    prefix: "ARMOutputs."

                - task: AzureFunctionApp@2
                  displayName: "Azure Function App Deploy: $(ARMOutputs.functionAppName)"
                  inputs:
                    azureSubscription: "${{ variables.DeploymentServiceConnectionName }}"
                    appType: functionApp
                    appName: "$(ARMOutputs.functionAppName)"
                    package: "$(System.DefaultWorkingDirectory)/$(FunctionsPackageName)/CustomerAppFunction.zip"
                    deploymentMode: runFromPackage
                    runtimeStack: 'DOTNET|6.0' 